[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "0eccd2aadd86d829a9c289d2848767715dfbd9bc"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "0b3054eecda01c871e266bd01a35f8ab91df81a6be5f8cdbe5de9a6c757c19c3"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.aarch64-linux-gnu.tar.gz"
[[FLINT]]
arch = "aarch64"
git-tree-sha1 = "f92ceca1a9c57f35abb535356fddf54cdba11b10"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "b1bccd67660b5078bd7882230931728e570fec89271c0d1e808e7ebe7270062f"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.aarch64-linux-musl.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "458e82bf0734d780dc640e298a4ecc97eed25117"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "28a5b852c9f96d6c6e23df38c81a5f69f8abbb69af2522e1c9397c3412854f10"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.armv7l-linux-gnueabihf.tar.gz"
[[FLINT]]
arch = "armv7l"
git-tree-sha1 = "01499d5e722b9eae8bc0439238df01db6f87d1af"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "4197f6156a6e128ff57d1ebd7ac922660192a714846d15b43c3d33e3284f214a"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.armv7l-linux-musleabihf.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "e46614da2cc6f88c407845c4fd545fb979537a17"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "082c5965c3fe715ab3a5cbbfdbde3e0113b65f07d564cf2cd8a7eb2f9ff2dba6"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.i686-linux-gnu.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "1e85cd6275e36f7545625a96f107ec05d445df9b"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "20503f47f8b8ea52e0580ab5c1484091d17cc53b26eb1b0e0e700b42374b5ff0"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.i686-linux-musl.tar.gz"
[[FLINT]]
arch = "i686"
git-tree-sha1 = "a3bc2d5c8bfe1667aac02a5a75a24492a1387c59"
os = "windows"

    [[FLINT.download]]
    sha256 = "a03faaf3dedf32d4b2cefbc4ac5eadbdaffb385ba7f00c835ad8c2ccaf4bd84c"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.i686-w64-mingw32.tar.gz"
[[FLINT]]
arch = "powerpc64le"
git-tree-sha1 = "93b9999c70ea6a6f439c5a68a8b90c6e0fe362f2"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "83cfb7e2ec8af1b66395f8241f69fdb46380a7114f49c89697a2c09fdbe0ac1c"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.powerpc64le-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "35f0ae1381334dc00204ecd59899007271803ba2"
os = "macos"

    [[FLINT.download]]
    sha256 = "5a78cf22d93c4951b3a530d8c06f7da8c92c42098bad8b31389298f32d14fb39"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.x86_64-apple-darwin14.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "95e785b6b61f7dd2d6b395dd21d320ae1a520fc1"
libc = "glibc"
os = "linux"

    [[FLINT.download]]
    sha256 = "2ec43d655d74ab4324e45a2c4d56760934baf0d0b24adb0d46e659395a4095cd"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.x86_64-linux-gnu.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "62efc6a06e0fae708c5a27df44a9059aca40d590"
libc = "musl"
os = "linux"

    [[FLINT.download]]
    sha256 = "eb2997a8f0336f8fb6c85f3e7e798505b1f70f8bb8b1473231199923442d8668"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.x86_64-linux-musl.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "4617a5fab86f9072390b35b48cdd9eeb9b0b7faf"
os = "freebsd"

    [[FLINT.download]]
    sha256 = "ccc9126477375ce915b57eb866a7915f719424dcd40b67be719e57874cffa287"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.x86_64-unknown-freebsd11.1.tar.gz"
[[FLINT]]
arch = "x86_64"
git-tree-sha1 = "9978a9db1fd9850acac9f51e77ef72f7916a6c5f"
os = "windows"

    [[FLINT.download]]
    sha256 = "476273b7a47bed64fab5e008333a164db97bbfb9b27c239c7a6fdb5fc6e2462b"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/FLINT-v2.7.0-dev+0/FLINT.v2.7.0-dev.x86_64-w64-mingw32.tar.gz"

[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e705d99c04675831da59121db58ef07e3076ddb5"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "8c12e7e233b7b75c717bd7bdb1b8b164f4002afd92cc5235f5ba2fb0c3fd218a"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.aarch64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95c23b5d9448b54043feefb334e2adf881150e33"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "a6214526adda10d876fa8bc0a4cf5e28511ebef275d99ec93638c97553d6842e"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a101a3384d0d832034c32da0031d9d52b7a0eb44"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "37e525513f409515771b116be7515a897991ff59cd5a6c9fdff28c8e7eb974fc"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.aarch64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aba9addde714ce3a2050ca88301e0b8c7dcfee1"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "f4d809bf33c2d9bd1d7b87a414ad23ccee206d9f3e3473765c7d3544e8fd9afa"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d37f6a957dc37b8fdcc7f9765fd2304e0da055b4"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "65914bf2f3c0ed9b2ebf87af79ad2e45cbb2f2438c6cb1e2d67ddc4ea4595169"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9bebf4876797216aad700ca2398e542384fb699"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "4211bf0370642e6d698db880d6816f5a76ca583e69890b4e20032d24baf00964"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fd95eee025a17b6eeeb12ff2a444ed87e48149d"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "42bab77d29791902365aa640375a68310cd1a57c1b76bded009e542370be1f6f"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Singular]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb3625db6cafc109404e0a39ad7a23069705e923"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "1f55c00e281799916ffdfb6ce30f32b7c9d446a9c47cf351af3bda4f6eba09fa"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f779697eb9d30eff50dac89df1a3f8f6e443b94d"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "0c14d76f48773e481a6b2d1205439ab8b2473c7dba3d72cc9ddbafd6320de450"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.i686-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08529be9be139cb351e1998d88c0591dc29511f6"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "fff70724221e51cf072713efd671f5b0464019305a12b8a6051cd8ef0230501f"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dda3a454f4286f414cf2f9b1b66a67c2f5e30d0"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "07362d837b6d433207408b250defe74e2bba0fb8d8e7022b5ea6eae27ec82418"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.i686-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d424281995f9fbf159ba95b88aec6273578de957"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "c691d849904d0746776f1f75e467533dab8e613fef74365ef805ebd9df71ca9b"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2ae3788d7d2daab81a2c4fd68a5c910fe596840"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e2f67d0dc142b83749e2c737e1bc8abf61f2e65b42d971418e4f3e1eb20a4434"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dc50824adfefb6409b32f68aba8fb3fb2a41334"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e5f3b88cd76c618f1d72934492b1f1a1daffe3d4637599668c40b7602ea7001a"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3993a227bbc7d7da5d3c9d5f09a380cfa55a022"
os = "macos"

    [[Singular.download]]
    sha256 = "38fad9087f349c0deafa2ca73e1f219e88e1823ce03d188d93cc96456c2da396"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-apple-darwin14-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d65fa5a5022b13ab500ab407df4a23271ffbacee"
os = "macos"

    [[Singular.download]]
    sha256 = "7aceadb1ec25fcfaa3a296b437230337451e1d7fc96b513cde68bd5317b9eb27"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-apple-darwin14-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbe404df92a88c2ac6f0d391f68cf18fd6b49ac1"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e4f33dd582bc2a5cfb5685b0d44cdb9ccc601a8e8262da365b804d3251ca8845"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-linux-gnu-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c6d7b1234de748965e6978971de06ca3560116e"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "8a6f50742bf8f25a1039c3236760a020196b2c0aa6c957d171ae70e7c465049c"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d93177aa766b93ee42da98573697191c7eb3269d"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "a039508a1c86e93014f915416a318214a4fd71a6bfdbafa5ea25887cd45aefa1"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-linux-musl-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d54c84d5314967747b9c89c05cd2c3f594e6c62f"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "a2cf5cb123ec3918e1aef40a07ce3f6df6b2a8b8371b51ea1b1a81463dd2bf0c"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69b079643d682ed0db2c6f46415f2a74d832bdd5"
os = "freebsd"

    [[Singular.download]]
    sha256 = "f15c7b6dbf25c373587d430ce1c6dee458fd0dd438d4d46a240d7d284bbdbaa4"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ed36beb30004dc5349254c84442ffdc10d80ded"
os = "freebsd"

    [[Singular.download]]
    sha256 = "1e047035c381350d3eb252810eae9ed322e9465def282f417e61f787c46194ae"
    url = "https://github.com/oscar-system/Singular_jll.jl/releases/download/Singular-v4.1.4-DEV+0/Singular.v4.1.4-DEV.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
